schema: "classroom50/repo-config/v1"
classroom: "indprog"
assignment: "02-conveyor-belt"
owner:
  username: "AndreasHallenberg"
  id: 323136145
  accepted_at: "2026-09-07T16:44:05Z"
source:
  owner: "indprog"
  owner_id: 316953525
  repo: "python-template"
  branch: "main"
